### ISSUE TITLE
When reloading the *inprogress.xml, i can't continue to annotate!

### ISSUE THREAD

**Issue by wai7niu8** [weitechen/anafora#28]
When reloading the *inprogress.xml, the schema is empty, but i don't know why.

**Comment by weitechen** [comment]
Could you open the Develop Tools and show me the error message in the console? Sorry Anafora has a horrible error display interface

**Comment by wai7niu8** [comment]
I found the reason after debugging the *.js in chrome. 
The "demomedicalschema.xml" in the sampleanaforaprojectfile of source code (anafora1.0.0 ) has entities type "UMLS CUI" which has whitespace.
