### ISSUE TITLE
Spelling mistake in **views.py** file

### ISSUE THREAD

**Issue by tpof314** [weitechen/anafora#53]
Hi, there is a spelling mistake in line 665 on the **master** branch.

```
  from django.core.exceptions import ImpoperlyConfigured
```
It should be **ImproperlyConfigured** instead of **ImpoperlyConfigured**. I found this error when I tried to configure it on my own computer.

**Comment by weitechen** [comment]
Thanks for the report. I fixed and committed in 7a7973faba460a98677c3f7e780664aa0e6238b6
