### ISSUE TITLE
Ampersand character is not correctly encoded in the XML output

### ISSUE THREAD

**Issue by dkincaid** [weitechen/anafora#55]
If a property of an entity or relation contains an ampersand (&) it has to be properly escaped as "&amp;". Instead the bare "&" character is being written to the XML. I assume this also applies to angle brackets ("<" and ">"), apostrophes (') and quotes (") as well. This causes the file to be unparsable. Here is an example:

```
	<entity>
		<id>19@e@262451_1_8970A-4_PD_2016-09-26 18_50_43.000000@jbraff</id>
		<span>1260,1268</span>
		<type>Diagnostic</type>
		<parentsType>Diseases</parentsType>
		<properties>
			<DiagnosticName>O&P fecal</DiagnosticName>
			<UMLSCUI></UMLSCUI>
			<Polarity>1</Polarity>
			<HistoryOf>No</HistoryOf>
			<Subject>patient</Subject>
			<Conditional>0</Conditional>
			<Context>labtest</Context>
		</properties>
	</entity>

```

**Comment by weitechen** [comment]
The XML escape characters are handled in the https://github.com/weitechen/anafora/blob/7a7973faba460a98677c3f7e780664aa0e6238b6/src/static/js/anafora/anaforaObj.js#L341-L343
